update

diff --git a/bush/compile_cpp b/bush/compile_cpp
--- a/bush/compile_cpp
+++ b/bush/compile_cpp
@@ -1,3 +1,5 @@
+# Copyright (C) 2010, Guy Barrand. All rights reserved.
+# See the file bush.license for terms.
 
 # to be sourced from another build script.
 
@@ -7,40 +9,61 @@ for file in ${C_files}  ; do echo ${file} >> cpp_tmp; done
 for file in ${cppfiles} ; do echo ${file} >> cpp_tmp; done
 
 if [ -f cpp_tmp ] ; then
-for file in $(cat cpp_tmp) ; do
-  oname=`basename ${file}`
 
-  oname=`echo ${oname} | sed -e 's:\.cc::g'`
-  oname=`echo ${oname} | sed -e 's:\.cxx::g'`
-  oname=`echo ${oname} | sed -e 's:\.C::g'`
-  oname=`echo ${oname} | sed -e 's:\.cpp::g'`
+parallel_found=yes
+${bush_home}/check_app parallel
+use_status=$?;if [ ${use_status} != 0 ] ; then parallel_found=no;fi
 
-  for item in ${archive_headers} ; do
-    if [ ${item} = ${oname} ] ; then
-      _cppflags="-DINLIB_TAKE_CODE"
-    fi
+if [ ${build_parallel} = yes -a ${parallel_found} = no ] ; then
+  echo 'bush/compile_cpp : -parallel but parallel not found. Continue without it.'
+fi
+
+if [ ${build_parallel} = yes -a ${parallel_found} = yes ] ; then
+
+  if [ ${build_verbose} = yes ] ; then
+    echo 'bush/compile_cpp : use parallel.'
+  fi
+  
+cat <<END > ./tmp_compile_one_cpp
+#!/bin/sh -f
+file=\$1
+build_o_ext=.parallel
+bush_home="${bush_home}"
+build_verbose="${build_verbose}"
+build_archive_headers="${archive_headers}"
+build_diro="${build_diro}"
+build_path="${build_path}"
+build_do_compile="${build_do_compile}"
+cpp_compiler="${cpp_compiler}"
+cppflags="${cppflags}"
+. ${bush_home}/compile_one_cpp
+END
+
+  chmod a+x ./tmp_compile_one_cpp
+  
+  ${bush_home}/find_rm ${build_path} '*.o.parallel'
+
+  parallel -a cpp_tmp './tmp_compile_one_cpp {}'
+
+  /bin/rm -f ./tmp_objs
+  find ${build_path} -name '*.o.parallel' -print >> ./tmp_objs
+
+  for item in $(cat ./tmp_objs) ; do
+    obj="`echo ${item} | sed -e 's:.parallel::g'`"
+    /bin/mv ${item} ${obj}
+    objs="${objs} ${obj}"
   done
 
-  if [ "${build_diro}" = "yes" ] ; then
-    dname=`dirname ${file}`
-    diro=`basename ${dname}`
-    /bin/mkdir -p "${build_path}/${diro}"
-    obj="${build_path}/${diro}/${oname}.o"
-  else
-    obj="${build_path}/${oname}.o"
-  fi
+  /bin/rm -f ./tmp_objs ./tmp_compile_one_cpp
 
-  if [ ${build_do_compile} = "yes" ] ; then
-    if [ ${build_verbose} = yes ] ; then
-      echo "bush/compile_cpp : do ${file} ..."
-    fi
-    if [ -f ${obj} ] ; then
-      echo "bush/compile_cpp : WARNING : ${obj} already exists."
-    fi
-    eval ${cpp_compiler} -x c++ -c ${cppflags} ${_cppflags} -o ${obj} ${file}
-    use_status=$?;if [ ${use_status} != 0 ] ; then exit ${use_status};fi
-  fi
-  objs="${objs} ${obj}"
-done
+else
+
+  for file in $(cat cpp_tmp) ; do
+    . ${bush_home}/compile_one_cpp
+  done
+
+fi
+
 /bin/rm -f cpp_tmp
+
 fi
diff --git a/bush/use_cc b/bush/use_cc
--- a/bush/use_cc
+++ b/bush/use_cc
@@ -1,28 +1,33 @@
+# Copyright (C) 2010, Guy Barrand. All rights reserved.
+# See the file bush.license for terms.
 
 cc_compiler=cc_not_defined
 
 ccflags=
 mflags=
+cc_linker_flags=
 
 if [ ${build_gnu} = "yes" ] ; then
   config_name=gnu
-  is_10_9=no
   if [ `uname` = Darwin ] ; then
     osx_vers="`sw_vers -productVersion`"
-    if [ "`echo ${osx_vers} | sed -e 's:10.9::g'`" != "${osx_vers}" ] ; then is_10_9=yes;fi
-  fi
-  if [ "${is_10_9}" = "yes" ] ; then
-    cc_compiler=/opt/local/bin/gcc-mp-4.8
-    cc_linker=/opt/local/bin/gcc-mp-4.8
+    if [ "`echo ${osx_vers} | sed -e 's:10.6::g'`" != "${osx_vers}" ] ; then # old screenwall macs.
+      cc_compiler=/opt/local/bin/gcc-mp-4.8
+      cc_linker=/opt/local/bin/gcc-mp-4.8
+    elif [ "`echo ${osx_vers} | sed -e 's:10.9::g'`" != "${osx_vers}" ] ; then
+      cc_compiler=/opt/local/bin/gcc-mp-4.8
+      cc_linker=/opt/local/bin/gcc-mp-4.8
+    elif [ "`echo ${osx_vers} | sed -e 's:10.12::g'`" != "${osx_vers}" ] ; then
+      cc_compiler=/opt/local/bin/gcc-mp-5
+      cc_linker=/opt/local/bin/gcc-mp-5
+    else
+      echo 'bush/use_cc : gcc not found under /opt/local/bin.'
+      exit
+    fi
   else
     cc_compiler=gcc
     cc_linker=gcc
   fi
-
-elif [ ${build_gnu_11} = "yes" ] ; then
-  config_name=gnu_11
-  cc_compiler="gcc"
-  cc_linker=gcc
 
 elif [ ${build_intel} = "yes" ] ; then
   config_name=intel
@@ -31,8 +36,24 @@ elif [ ${build_intel} = "yes" ] ; then
 
 elif [ ${build_clang} = "yes" ] ; then
   config_name=clang
-  cc_compiler=clang
-  cc_linker=clang
+  
+  found=no
+  items="clang clang-3.9 clang-3.5 clang-3.4 clang-3.3"
+  for item in ${items} ; do
+    ${bush_home}/check_app ${item}
+    use_status=$?;
+    if [ ${use_status} = 0 ] ; then
+      cc_compiler=${item}
+      cc_linker=${item}
+      found=yes
+      break
+    fi
+  done
+
+  if [ ${found} = no ] ; then
+    echo "${items} not found."
+    exit
+  fi
 
 elif [ ${build_sdk_mac} = "yes" -o ${build_sdk_mac_gnu} = "yes" ] ; then
 
@@ -49,37 +70,28 @@ elif [ ${build_sdk_mac} = "yes" -o ${build_sdk_mac_gnu} = "yes" ] ; then
     cc_linker=gcc
   fi
 
-  # see also use_cpp :
-  sdk_dirs="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs /Developer/SDKs"
-  sdk_verss="10.11 10.9 10.8 10.6 10.5"
-  found=no
-  for sdk_dir in ${sdk_dirs} ; do
-    for sdk_vers in ${sdk_verss} ; do
-      if [ ${found} = no ] ; then
-        macosx_sdk="${sdk_dir}/MacOSX${sdk_vers}.sdk"
-        macosx_vers=${sdk_vers}
-        if [ -d "${macosx_sdk}" ] ; then found=yes;fi
-      fi
-    done
-  done
-  if [ ${found} = no ] ; then
-    echo "bush/use_cc : MacOSX sdk not found."
-    exit
+  osx_vers="`sw_vers -productVersion`"
+  if [ "`echo ${osx_vers} | sed -e 's:10.6::g'`" != "${osx_vers}" ] ; then # old screenwall macs.
+    macosx_sdk="/Developer/SDKs/MacOSX10.6.sdk"
+    if [ ! -d "${macosx_sdk}" ] ; then
+      echo "bush/use_cc : MacOSX.sdk sdk not found at ${macosx_sdk}."
+      exit
+    fi
+  else
+    macosx_sdk="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
   fi
-  #echo "${macosx_sdk}"
-  #echo "${macosx_vers}"
 
-  macosx_target=10.6  # wall machines
+ #macosx_target=10.6  # old screenwall macs.
   macosx_target=10.5  # old mac
 
-  cc_compiler="${cc_compiler} -isysroot ${macosx_sdk}"
-  cc_compiler="${cc_compiler} -mmacosx-version-min=${macosx_target}"
+  ccflags="${ccflags} -isysroot ${macosx_sdk}"
+  ccflags="${ccflags} -mmacosx-version-min=${macosx_target}"
 
-  cc_linker="${cc_linker} -isysroot ${macosx_sdk}"
+  cc_linker_flags="${cc_linker_flags} -isysroot ${macosx_sdk}"
 
   if [ `uname -p` = x86_64 ] ; then
-    cpp_compiler="${cpp_compiler} -arch x86_64"
-    cpp_linker="${cpp_linker} -arch x86_64"
+    ccflags="${ccflags} -arch x86_64"
+    cc_linker_flags="${cc_linker_flags} -arch x86_64"
   fi
 
   #LANG=en_US.US-ASCII
@@ -88,6 +100,23 @@ elif [ ${build_sdk_mac} = "yes" -o ${build_sdk_mac_gnu} = "yes" ] ; then
   MACOSX_DEPLOYMENT_TARGET=${macosx_target}
   export MACOSX_DEPLOYMENT_TARGET
 
+elif [ ${build_cling_clang} = "yes" ] ; then
+  config_name=cling_clang
+
+  . ${bush_home}/use_cling
+  
+  if [ "${cling_home}" = "" ] ; then
+    echo "bush/use_cc : cling_home not defined."
+    exit
+  fi
+  
+  if [ ${build_verbose} = yes ] ; then
+    echo "bush/use_cc : cling_home is ${cling_home}."
+  fi
+
+  cc_compiler=${cling_home}/bin/clang
+  cc_linker=${cpp_compiler}
+  
 elif [ ${build_sdk_ios} = "yes" -o ${build_sdk_ios_gnu} = "yes" ] ; then
 
   # options taken from the output of :
@@ -100,40 +129,55 @@ elif [ ${build_sdk_ios} = "yes" -o ${build_sdk_ios_gnu} = "yes" ] ; then
   else
     config_name=sdk_ios_gnu
     cc_compiler=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/llvm-gcc-4.2
-    cc_linker=${cpp_compiler}
+    cc_linker=${cc_compiler}
   fi
 
   # see also use_cpp :
-  sdk_dirs="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs /Developer/SDKs"
-  sdk_verss="9.0 8.1 7.1 5.0"
-  found=no
-  for sdk_dir in ${sdk_dirs} ; do
-    for sdk_vers in ${sdk_verss} ; do
-      if [ ${found} = no ] ; then
-        ios_sdk="${sdk_dir}/iPhoneOS${sdk_vers}.sdk"
-        ios_vers=${sdk_vers}
-        if [ -d "${ios_sdk}" ] ; then found=yes;fi
-      fi
-    done
-  done
-  if [ ${found} = no ] ; then
-    echo "bush/use_cc : iOS sdk not found."
-    exit
-  fi
+  #sdk_dirs="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs /Developer/SDKs"
+  #sdk_verss="10.0 9.3 9.0 8.1 7.1 5.0"
+  #found=no
+  #for sdk_dir in ${sdk_dirs} ; do
+  #  for sdk_vers in ${sdk_verss} ; do
+  #    if [ ${found} = no ] ; then
+  #      ios_sdk="${sdk_dir}/iPhoneOS${sdk_vers}.sdk"
+  #      ios_vers=${sdk_vers}
+  #     if [ -d "${ios_sdk}" ] ; then found=yes;fi
+  #   fi
+  # done
+  #done
+  #if [ ${found} = no ] ; then
+  #  echo "bush/use_cc : iOS sdk not found."
+  #  exit
+  #fi
   #echo "${ios_sdk}"
   #echo "${ios_vers}"
   #exit
 
+  ios_sdk="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk"
+  if [ ! -d "${ios_sdk}" ] ; then
+    echo "bush/use_cc : iPhoneOS.sdk not found at ${ios_sdk}."
+    exit
+  fi
+
   ios_target=3.2
 
-  cc_compiler="${cc_compiler} -arch armv7 -pipe -isysroot ${ios_sdk}"
+  # NOTE : have all known arch of Xcode to be able to link ioda with libourex_CoinGL.a from Xcode.
+  archs="-arch arm64 -arch armv7 -arch armv7s"
 
-  cc_linker="${cc_linker} -arch armv7 -isysroot ${ios_sdk}"
-  cc_linker="${cc_linker} -miphoneos-version-min=${ios_target}"
+  ccflags="${ccflags} ${archs} -pipe -isysroot ${ios_sdk}"
+
+  cc_linker_flags="${cc_linker_flags} ${archs} -isysroot ${ios_sdk}"
+  cc_linker_flags="${cc_linker_flags} -miphoneos-version-min=${ios_target}"
 
   ccflags="${ccflags} -miphoneos-version-min=${ios_target}"
 
- #ccflags="${ccflags} -gdwarf-2 -fvisibility=hidden -mno-thumb" 
+  # NOTE : to link ioda with libourex_CoinGL.a from Xcode :
+  ccflags="${ccflags} -fembed-bitcode"
+
+  # the below is to stay consistent with use_cpp :
+  ccflags="${ccflags} -fvisibility=hidden"
+
+ #ccflags="${ccflags} -gdwarf-2 -mno-thumb" 
  #ccflags="${ccflags} -Os"
 
   mflags="${mflags} -fobjc-abi-version=2 -fobjc-legacy-dispatch"
@@ -149,17 +193,18 @@ elif [ ${build_sdk_iossim} = "yes" ] ; then
   cc_compiler=clang
   cc_linker=clang
 
-  ios_vers=5.0
-  ios_sdk="/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator${ios_vers}.sdk"
+  ios_sdk="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk"
   if [ ! -e "${ios_sdk}" ] ; then
-    echo 'bush/use_cc : iOS sdk not found.'
+    echo 'bush/use_cc : iPhoneSimulator sdk not found at ${ios_sdk}.'
     exit
   fi
 
-  cc_compiler="${cc_compiler} -arch i386 -pipe -isysroot ${ios_sdk}"
+  ios_target=5.0
 
-  cc_linker="${cc_linker} -arch i386 -isysroot ${ios_sdk}"
-  cc_linker="${cc_linker} -miphoneos-version-min=${ios_vers}"
+  ccflags="${ccflags} -arch i386 -pipe -isysroot ${ios_sdk}"
+
+  cc_linker_flags="${cc_linker_flags} -arch i386 -isysroot ${ios_sdk}"
+  cc_linker_flags="${cc_linker_flags} -miphoneos-version-min=${ios_target}"
 
   mflags="${mflags} -fobjc-abi-version=2 -fobjc-legacy-dispatch"
   ccflags="${ccflags} -D__IPHONE_OS_VERSION_MIN_REQUIRED=30200"
@@ -168,7 +213,7 @@ elif [ ${build_visual} = "yes" ] ; then
   config_name=visual
 
   if [ "${bush_home}" = "" ] ; then
-    echo "bush/use_cpp : build_visual : bush_home not defined."
+    echo "bush/use_cc : build_visual : bush_home not defined."
     exit
   fi
   cc_compiler=${bush_home}/vc++
@@ -177,15 +222,31 @@ elif [ ${build_visual} = "yes" ] ; then
 
   cc_linker=${bush_home}/vc++
 
+  if [ "${build_set_x}" = "yes" ] ; then cc_linker_flags="${cc_linker_flags} -verbose"; fi
+
 elif [ ${build_sdk_android} = "yes" ] ; then
   config_name=sdk_android
 
   sdk_home=/usr/local/Android/android-sdk_r16-macosx
-  ndk_home=/usr/local/Android/android-ndk-r7
 
-  ndk_bin=${ndk_home}/toolchains/arm-linux-androideabi-4.4.3/prebuilt/darwin-x86/bin
+  # WARNING : must be in sync with use_cpp, plugin, use/Android.
 
-  ndk_platform="${ndk_home}/platforms/android-9/arch-arm"
+ #build_ndk_vers=r15b
+  build_ndk_vers=r7
+  build_ndk_vers=r10e
+  
+  ndk_home=/usr/local/Android/android-ndk-${build_ndk_vers}
+
+  if [ ${build_ndk_vers} = r7 ] ; then
+    ndk_bin=${ndk_home}/toolchains/arm-linux-androideabi-4.4.3/prebuilt/darwin-x86/bin
+    ndk_platform="${ndk_home}/platforms/android-9/arch-arm"
+  elif [ ${build_ndk_vers} = r10e ] ; then
+    ndk_bin=${ndk_home}/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin
+    ndk_platform="${ndk_home}/platforms/android-9/arch-arm"
+  else
+    echo "bush/use_cc : ndk version ${build_ndk_vers} not yet supported."
+    exit
+  fi    
 
   cc_compiler=${ndk_bin}/arm-linux-androideabi-gcc
 
@@ -194,19 +255,30 @@ elif [ ${build_sdk_android} = "yes" ] ; then
  #ccflags="${ccflags} -Ijni"
  #ccflags="${ccflags} -I${ndk_home}/sources/cxx-stl/system/include"
 
+  if [ ${build_ndk_vers} = r7 ] ; then
+    ccflags="${ccflags} -D__ARM_ARCH_5__ -D__ARM_ARCH_5T__"
+    ccflags="${ccflags} -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__"
+  fi
+  
   ccflags="${ccflags} -fpic"
-  ccflags="${ccflags} -D__ARM_ARCH_5__ -D__ARM_ARCH_5T__"
-  ccflags="${ccflags} -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__"
-  ccflags="${ccflags} -Wno-psabi -march=armv5te -mtune=xscale -msoft-float"
-  ccflags="${ccflags} -mthumb"
-  ccflags="${ccflags} -Os"
-  ccflags="${ccflags} -Wa,--noexecstack"
   ccflags="${ccflags} -ffunction-sections -funwind-tables -fstack-protector"
   ccflags="${ccflags} -fomit-frame-pointer -fno-strict-aliasing"
   ccflags="${ccflags} -finline-limit=64"
+  
+  ccflags="${ccflags} -mthumb"
+  ccflags="${ccflags} -Os"
+  ccflags="${ccflags} -march=armv5te -mtune=xscale -msoft-float"
+
+  ccflags="${ccflags} -Wno-psabi -Wa,--noexecstack"
+  
   ccflags="${ccflags} -I${ndk_platform}/usr/include"
+  
   ccflags="${ccflags} -DANDROID"
 
+  if [ ${build_ndk_vers} = r10e ] ; then
+    ccflags="${ccflags} -no-canonical-prefixes -Wformat -Werror=format-security"
+  fi
+  
   cc_linker=${cc_compiler}
 
 else
@@ -216,7 +288,12 @@ fi
 
 if [ ${build_visual} = "yes" ] ; then
 
-  echo dummy > /dev/null
+  if [ ${build_debug} = "yes" ] ; then
+    ccflags="${ccflags} -g"
+    cc_linker_flags="${cc_linker_flags} -g"
+  else    
+    ccflags="${ccflags} -DNDEBUG"
+  fi
 
 else
 
@@ -224,6 +301,7 @@ else
     ccflags="${ccflags} -g"
   else
     ccflags="${ccflags} -O2"
+    ccflags="${ccflags} -DNDEBUG"
   fi
 
   if [ ${build_m32} = yes ] ; then ccflags="${ccflags} -m32"; fi
